/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionBase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul Garcia
 */
public class Marca extends javax.swing.JInternalFrame {
    String nombre;
    DefaultTableModel model;
    
    
    /**
     * Creates new form Marca
     */
    public Marca() {
        initComponents();
        btnNuevo.setEnabled(false);
        //txtNombreMarca.requestFocus(true);
        //llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void registrarMarca(){
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_agregarmarca(?,?,?)}");
        instruccionBD.add(txtNombreMarca.getText());
        instruccionBD.add(txtTelefono.getText());
        instruccionBD.add(txtContacto.getText());
        ConexionBase objCBD=new ConexionBase();
        objCBD.ejecutarABC(instruccionBD);
        JOptionPane.showMessageDialog(null,"Registro con éxito");
        limpiar();
    }
    
    
    private void consultarRegistroMarca(String texto){
        nombre = JOptionPane.showInputDialog(null,"Marca a " + texto);
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_consultarmarca(?)}");
        instruccionBD.add(nombre);
        ConexionBase objCBD=new ConexionBase();
        ResultSet cdr=objCBD.ejecutarConsula(instruccionBD);
        mostrarDatos(cdr);
        deshabilitarBotones("consultas");
    }
    
    private void mostrarDatos(ResultSet cdr){
        try {
            while (cdr.next()){
                try {
                    txtNombreMarca.setText(cdr.getString(2));
                    txtTelefono.setText(cdr.getString(3));
                    txtContacto.setText(cdr.getString(4));
                } catch (SQLException ex) {
                    
                    //JOptionPane.showMessageDialog(null,"No existe registro");
                }
            }
        } catch (SQLException ex) {
            
        }
    }
    
    public void eliminarMarca(){
        if (btnBajas.getText().equalsIgnoreCase("Bajas")){
            consultarRegistroMarca("eliminar");
            btnBajas.setText("confirmar");
            deshabilitarBotones("bajas");
        } else {
            ArrayList instruccionBD = new ArrayList();
            instruccionBD.add("{call sp_eliminarmarca(?)}");
            instruccionBD.add(nombre);
            ConexionBase objCBD=new ConexionBase();
            objCBD.ejecutarABC(instruccionBD);
            habilitarBotones();
            limpiar();
            JOptionPane.showMessageDialog(null,"Registro eliminado");
        }
    }
    
    private void deshabilitarBotones(String texto){
        switch (texto){
            case "altas":
                btnBajas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnConsultas.setEnabled(false);
            break;    
            case "bajas":
                btnAltas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnConsultas.setEnabled(false);
                btnNuevo.setEnabled(false);
                btnBajas.setEnabled(true);
            break; 
            case "cambios":
                btnBajas.setEnabled(false);
                btnAltas.setEnabled(false);
                btnConsultas.setEnabled(false);
            break; 
            case "consultas":
                btnBajas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnAltas.setEnabled(false);
                btnNuevo.setEnabled(true);
            break; 
        }
    }
    
    private void habilitarBotones(){
        btnBajas.setEnabled(true);
        btnCambios.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnAltas.setEnabled(true);
        btnBajas.setText("Bajas");
        btnConsultas.setText("Consultas");
    }
    
    private void limpiar(){
        txtNombreMarca.setText(null);
        txtTelefono.setText(null);
        txtContacto.setText(null);
    }
    
    private void limpiarCat(){
        txtCat.setText(null);
        
    }
    
    public void agregarCat(){
        model=(DefaultTableModel)this.tablaCategorias.getModel();
        model.addRow(new Object[1]);
        //for (int x=0;x<this.tblCategorias.getColumnCount()-1;x++){
            model.setValueAt(txtCat.getText(),(model.getRowCount()-1),0);
            
        //}
        //filas++;
    }
    
    private void registrarCategoria(){
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_agregarcategoria(?)}");
        instruccionBD.add(txtCat.getText());
        ConexionBase objCBD=new ConexionBase();
        objCBD.ejecutarABC(instruccionBD);
        JOptionPane.showMessageDialog(null,"Registro con éxito");
        limpiarCat();
    }
    
    private void consultarCategoria(){
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_consultarcategoria()}");
        ConexionBase objCBD=new ConexionBase();
        ResultSet cdr=objCBD.ejecutarConsula(instruccionBD);
        mostrarDatosCategoria(cdr);
    }
    
    private void mostrarDatosCategoria(ResultSet cdr){
        model=(DefaultTableModel)this.tablaCategorias.getModel();
        int filas = 0;
            try {
                while(cdr.next()){
                model.addRow(new Object[1]);
                model.setValueAt(cdr.getString(2),filas,0);
                filas++;
                }
            } catch (SQLException ex) {
                System.out.println("Error "+ex);
            }
        
        
        
        /*try {
            
            while (cdr.next()){
                try {
                    
                    txtCT.setText(cdr.getString(1));
                } catch (SQLException ex) {
                    
                    //JOptionPane.showMessageDialog(null,"No existe registro");
                }
            }
        } catch (SQLException ex) {
            
        }*/
        
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        txtCat = new javax.swing.JTextField();
        btnMas = new javax.swing.JButton();
        txtContacto = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAltas = new javax.swing.JButton();
        btnBajas = new javax.swing.JButton();
        btnCambios = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categorias"
            }
        ));
        jScrollPane1.setViewportView(tablaCategorias);

        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la marca");

        jLabel2.setText("Nombre del contacto");

        jLabel3.setText("Telefono");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pape3.jpg"))); // NOI18N

        btnAltas.setText("Altas");
        btnAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltasActionPerformed(evt);
            }
        });

        btnBajas.setText("Bajas");
        btnBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajasActionPerformed(evt);
            }
        });

        btnCambios.setText("Cambios");
        btnCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiosActionPerformed(evt);
            }
        });

        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel5.setText("Registra Marca y/o Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAltas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBajas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMas)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnBajas))
                            .addComponent(btnAltas))
                        .addGap(10, 10, 10)
                        .addComponent(btnCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultas)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltasActionPerformed
        registrarMarca();
    }//GEN-LAST:event_btnAltasActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        consultarRegistroMarca("consultar");
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajasActionPerformed
        eliminarMarca();
    }//GEN-LAST:event_btnBajasActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        agregarCat();
        registrarCategoria();
        //consultarCategoria();
    }//GEN-LAST:event_btnMasActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        consultarCategoria();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiosActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        habilitarBotones();
        btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAltas;
    public javax.swing.JButton btnBajas;
    public javax.swing.JButton btnCambios;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnMas;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTextField txtCat;
    public javax.swing.JTextField txtContacto;
    public javax.swing.JTextField txtNombreMarca;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
