/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.ConexionBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul Garcia
 */
public class Productos extends javax.swing.JInternalFrame {
    String nombre;
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        llenarcmbCategorias();
        llenarcmbMarca();
        btnNuevo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbMarca = new javax.swing.JComboBox<>();
        spStock = new javax.swing.JSpinner();
        btnAltas = new javax.swing.JButton();
        btnBajas = new javax.swing.JButton();
        btnCambios = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pape3.jpg"))); // NOI18N

        jLabel1.setText("Descripcion del producto");

        jLabel2.setText("Categoría");

        jLabel3.setText("Marca");

        jLabel4.setText("Stock");

        jLabel5.setText("Costo");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona..." }));

        btnAltas.setText("Altas");
        btnAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltasActionPerformed(evt);
            }
        });

        btnBajas.setText("Bajas");

        btnCambios.setText("Cambios");

        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setText("Registrar Producto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spStock, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(btnNuevo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAltas)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBajas)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCambios)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnConsultas)))
                            .addGap(57, 57, 57)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltas)
                    .addComponent(btnBajas)
                    .addComponent(btnCambios)
                    .addComponent(btnConsultas))
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltasActionPerformed
        registrarProducto();
    }//GEN-LAST:event_btnAltasActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        consultarRegistroProducto("consultar");
        consultarCategoriaYMarca();
        deshabilitarBotones("consultas");
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        habilitarBotones();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void registrarProducto(){
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_agregarproducto(?,?,?,?,?)}");
        instruccionBD.add(cmbCategoria.getSelectedItem());
        instruccionBD.add(txtDescripcion.getText());
        instruccionBD.add(spStock.getValue());
        instruccionBD.add(txtCosto.getText());
        instruccionBD.add(cmbMarca.getSelectedItem());
        ConexionBase objCBD=new ConexionBase();
        objCBD.ejecutarABC(instruccionBD);
        JOptionPane.showMessageDialog(null,"Registro con éxito");
        limpiar();
        
    }
    
    private void consultarRegistroProducto(String texto){
        nombre = JOptionPane.showInputDialog(null,"Producto a " + texto);
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_consultarproducto(?)}");
        instruccionBD.add(nombre);
        ConexionBase objCBD=new ConexionBase();
        ResultSet cdr=objCBD.ejecutarConsula(instruccionBD);
        mostrarDatos(cdr);
    }
    
    private void mostrarDatos(ResultSet cdr){
        try {
            while (cdr.next()){
                try {
                    txtDescripcion.setText(cdr.getString(1));
                    spStock.setValue(Integer.parseInt(cdr.getString(2)));
                    txtCosto.setText(cdr.getString(3));
                } catch (SQLException ex) {
                    
                    //JOptionPane.showMessageDialog(null,"No existe registro");
                }
            }
        } catch (SQLException ex) {
            
        }
    }
    
    
    private void consultarCategoriaYMarca(){
        nombre = txtDescripcion.getText();
        ArrayList instruccionBD=new ArrayList();
        instruccionBD.add("{call sp_consultarcatymarca(?)}");
        instruccionBD.add(nombre);
        ConexionBase objCBD=new ConexionBase();
        ResultSet cdr=objCBD.ejecutarConsula(instruccionBD);
        mostrarDatosCategoriaYMarca(cdr);
    }
    
    private void mostrarDatosCategoriaYMarca(ResultSet cdr){
        try {
            while (cdr.next()){
                try {
                    cmbCategoria.setSelectedItem(cdr.getString(1));
                    cmbMarca.setSelectedItem(cdr.getString(2));
                } catch (SQLException ex) {
                    
                    //JOptionPane.showMessageDialog(null,"No existe registro");
                }
            }
        } catch (SQLException ex) {
            
        }
    }
    
    private void llenarcmbCategorias(){
        ResultSet table=ConexionBase.getInstance().consultar("SELECT * FROM categoria");
        try{
            while(table.next()){
                cmbCategoria.addItem(table.getString(2));
            }
        }catch(SQLException ex){
            //Nothing to do
            ex.printStackTrace();
        }
    }
    
    
    private void llenarcmbMarca(){
        ResultSet table=ConexionBase.getInstance().consultar("SELECT * FROM marca");
        try{
            while(table.next()){
                cmbMarca.addItem(table.getString(2));
            }
        }catch(SQLException ex){
            //Nothing to do
            ex.printStackTrace();
        }
    }
    
    public void eliminarMarca(){
        if (btnBajas.getText().equalsIgnoreCase("Bajas")){
            consultarRegistroProducto("eliminar");
            btnBajas.setText("confirmar");
            deshabilitarBotones("bajas");
        } else {
            ArrayList instruccionBD = new ArrayList();
            instruccionBD.add("{call sp_eliminarproducto(?)}");
            instruccionBD.add(nombre);
            ConexionBase objCBD=new ConexionBase();
            objCBD.ejecutarABC(instruccionBD);
            habilitarBotones();
            limpiar();
            JOptionPane.showMessageDialog(null,"Registro eliminado");
        }
    }
    
    private void habilitarBotones(){
        btnBajas.setEnabled(true);
        btnCambios.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnAltas.setEnabled(true);
        btnNuevo.setEnabled(false);
    }
    
    private void deshabilitarBotones(String texto){
        switch (texto){
            case "altas":
                btnBajas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnConsultas.setEnabled(false);
            break;    
            case "bajas":
                btnAltas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnConsultas.setEnabled(false);
            break; 
            case "cambios":
                btnBajas.setEnabled(false);
                btnAltas.setEnabled(false);
                btnConsultas.setEnabled(false);
            break; 
            case "consultas":
                btnBajas.setEnabled(false);
                btnCambios.setEnabled(false);
                btnAltas.setEnabled(false);
                btnNuevo.setEnabled(true);
            break; 
        }
    }
    
    private void limpiar(){
        txtDescripcion.setText(null);
        cmbCategoria.setSelectedIndex(0);
        cmbMarca.setSelectedIndex(0);
        spStock.setValue(0);
        txtCosto.setText(null);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAltas;
    public javax.swing.JButton btnBajas;
    public javax.swing.JButton btnCambios;
    public javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cmbCategoria;
    public javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JSpinner spStock;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
